### ISSUE TITLE
How to insert hyperparameters into train.py in the DrQA repo

### ISSUE THREAD

**Issue by YunqiuXu** [rajammanabrolu/KG-DQN#2]
Should I insert them as new items in function "add_train_args()", if so, what argument group should be for them? Or should I change those related parameters in drqa.reader.config instead, e.g. assign '--hidden-size' as 64?

```
# drqa.reader.config
# group "DrQA Reader Model Architecture"
DrQA Reader Model Architecture
--hidden-size
--doc-layers

# group "DrQA Reader Model Details"
--concat-rnn-layers

# group "DrQA Reader Optimization"
--dropout-rnn
--dropout-rnn-output
--rnn-padding
```

```
# README.md
'doc_hidden_size': 64,
'doc_layers': 3,
'doc_dropout_rnn': 0.2,
'doc_dropout_rnn_output': True,
'doc_concat_rnn_layers': True,
'doc_rnn_padding': True
```

**Comment by rajammanabrolu** [comment]
The DrQA interface has changed since it was first used for this paper but yes, all of the parameters correspond to the reader.config but are now spread out over multiple groups.
